AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/pulse-zero.rb'
    - 'lib/pulse_zero.rb'