name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']
        rails-version: ['7.0', '7.1', '7.2']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      env:
        RAILS_VERSION: ${{ matrix.rails-version }}
      run: |
        bundle exec rake test

    - name: Run RuboCop
      run: bundle exec rubocop

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Build gem
      run: |
        gem build pulse_zero.gemspec

    - name: Upload gem
      uses: actions/upload-artifact@v4
      with:
        name: pulse_zero-gem
        path: "*.gem"